#!/usr/bin/bash

# SCRIPT VERSION
USER_SETUP_VER=8
USER_SETUP_VER_FILE="${XDG_DATA_HOME:-${HOME}/.local/share}/ublue/user-setup"
USER_SETUP_VER_RAN=$(cat "${USER_SETUP_VER_FILE}")
VEN_ID="$(cat /sys/devices/virtual/dmi/id/chassis_vendor)"

mkdir -p "$(dirname "${USER_SETUP_VER_FILE}")" || exit 1

dirname "${USER_SETUP_VER_FILE}"

# INIT
UBLUE_CONFIG_DIR="${XDG_DATA_HOME:-${HOME}/.local/share}/ublue"
mkdir -p "${UBLUE_CONFIG_DIR}"

# Upgrade from v1 to v2 changes only the location of the USER_SETUP_VER.
# Exit if v1 file is present.
USER_SETUP_VER_FILE_V1="${HOME}/.ublue-configured"
if [[ -f ${USER_SETUP_VER_FILE_V1} ]]; then
	echo "User setup v1 has already run. Exiting..."
	rm "${USER_SETUP_VER_FILE_V1}"
	echo "${USER_SETUP_VER}" >"${USER_SETUP_VER_FILE}"
	exit 0
fi

# Run script if updated
if [[ -f ${USER_SETUP_VER_FILE} && ${USER_SETUP_VER} == "${USER_SETUP_VER_RAN}" ]]; then
	echo "User setup v${VER} has already run. Exiting..."
	exit 0
fi

# Enable Flathub
flatpak remote-add --if-not-exists --user flathub /etc/flatpak/remotes.d/flathub.flatpakrepo
flatpak remote-modify --user --enable flathub

# Currently unused
# IMAGE_INFO="/usr/share/ublue-os/image-info.json"
# IMAGE_NAME=$(jq -r '."image-name"' < $IMAGE_INFO)

if [[ ":Framework:" =~ :${VEN_ID}: ]]; then
	if [[ ! -f "${UBLUE_CONFIG_DIR}/framework-initialized" ]]; then
		echo 'Setting Framework logo menu'
		dconf write /org/gnome/shell/extensions/Logo-menu/symbolic-icon true
		dconf write /org/gnome/shell/extensions/Logo-menu/menu-button-icon-image 31
		echo 'Setting touch scroll type'
		dconf write /org/gnome/desktop/peripherals/mouse/natural-scroll true
		if [[ ${SYS_ID} == "Laptop ("* ]]; then
			echo 'Applying font fix for Framework 13'
			dconf write /org/gnome/desktop/interface/text-scaling-factor 1.25
		fi
		touch "${UBLUE_CONFIG_DIR}/framework-initialized"
	fi
fi

# Add shortcut to boot into windows
ujust setup-boot-windows

# Handle privileged tasks
pkexec /usr/libexec/ublue-privileged-user-setup

# Prevent future executions
echo "Writing state file"
echo "${USER_SETUP_VER}" >"${USER_SETUP_VER_FILE}"
