#!/usr/bin/bash

# Script Version
VER=2
VER_FILE="${XDG_DATA_HOME:-${HOME}/.local/share}/ublue/flatpak_manager_version"
VER_RAN=$(cat "${VER_FILE}")

mkdir -p "$(dirname "${VER_FILE}")" || exit 1

# Run script if updated
if [[ -f ${VER_FILE} && ${VER} == "${VER_RAN}" ]]; then
	echo "Flatpak manager v${VER} has already ran. Exiting..."
	exit 0
fi

# Ensure Flathub is enabled
flatpak remote-add --if-not-exists --system flathub /etc/flatpak/remotes.d/flathub.flatpakrepo
flatpak remote-modify --system --enable flathub

PROTONTRICKS_SETUP_FILE="/etc/bazzite/protontricks_installed"
if [[ ! -f ${PROTONTRICKS_SETUP_FILE} ]]; then
	if ! grep -q "com.github.Matoking.protontricks" <<<"$(/usr/bin/flatpak list --app --columns=application)"; then
		flatpak install --system --assumeyes com.github.Matoking.protontricks
		touch "${PROTONTRICKS_SETUP_FILE}"
	else
		touch "${PROTONTRICKS_SETUP_FILE}"
	fi
fi

# Flatpak theming support
flatpak override \
	--filesystem=xdg-config/gtk-4.0:ro \
	--filesystem=xdg-config/gtk-3.0:ro \
	--filesystem=xdg-data/icons:ro \
	--filesystem="${HOME}"/.themes:ro

# Fix printing on LibreOffice
flatpak override \
	--socket=cups \
	--socket=session-bus \
	org.libreoffice.LibreOffice

# Fix permissions for Protontricks
flatpak override \
	--filesystem=~/.local/share/Steam \
	--filesystem=/var/mnt \
	--filesystem=/run/media \
	com.github.Matoking.protontricks

# Fixes too many flatpaks to list
flatpak override \
	--socket=session-bus \
	--socket=system-bus \
	--socket=wayland

# Set up Zen default configuration
mkdir -p "/var/lib/flatpak/extension/io.github.zen_browser.zen.systemconfig/$(arch)/stable/defaults/pref"
rm -f "/var/lib/flatpak/extension/io.github.zen_browser.zen.systemconfig/$(arch)/stable/defaults/pref/{*sarkinite*,*arkenfox*}.js"
/usr/bin/cp -rf /usr/lib64/firefox/defaults/pref/* "/var/lib/flatpak/extension/io.github.zen_browser.zen.systemconfig/$(arch)/stable/defaults/pref/"

# Use until yafti rework is done
flatpak --system update -y

notify-send "Welcome to Sarkinite" "Your computer is ready!" --app-name="Flatpak Manager Service" -u NORMAL

echo "${VER}" >"${VER_FILE}"
