#!/usr/bin/bash

# Script Version
VER=6
VER_FILE="${XDG_DATA_HOME:-${HOME}/.local/share}/ublue/flatpak_manager_version"
VER_RAN=$(cat "${VER_FILE}")

mkdir -p "$(dirname "${VER_FILE}")" || exit 1

# Run script if updated
if [[ -f ${VER_FILE} && ${VER} == "${VER_RAN}" ]]; then
	echo "Flatpak manager v${VER} has already ran. Exiting..."
	exit 0
fi

# Ensure Flathub is enabled
flatpak remote-add --if-not-exists --system flathub /etc/flatpak/remotes.d/flathub.flatpakrepo
flatpak remote-modify --system --enable flathub

# Flatpak theming support
[[ ! -L ~/.local/share/themes ]] && ln -s /usr/share/themes ~/.local/share/themes
[[ ! -L ~/.local/share/icons ]] && ln -s /usr/share/icons ~/.local/share/icons
flatpak override \
	--system \
	--filesystem=xdg-config/gtk-4.0:ro \
	--filesystem=xdg-config/gtk-3.0:ro \
	--filesystem=xdg-data/applications:ro \
	--filesystem=xdg-data/themes:ro \
	--filesystem=xdg-data/icons:ro \
	--filesystem="${HOME}"/.themes:ro \
	--filesystem="${HOME}"/.icons:ro
flatpak override \
	--user \
	--filesystem=xdg-config/gtk-4.0:ro \
	--filesystem=xdg-config/gtk-3.0:ro \
	--filesystem=xdg-data/applications:ro \
	--filesystem=xdg-data/themes:ro \
	--filesystem=xdg-data/icons:ro \
	--filesystem="${HOME}"/.themes:ro \
	--filesystem="${HOME}"/.icons:ro

if [[ $(cat /etc/ublue/image_name) =~ "gnome" ]]; then
	flatpak override --env=XDG_CURRENT_DESKTOP=GNOME
	flatpak override --user --env=XDG_CURRENT_DESKTOP=GNOME
elif [[ $(cat /etc/ublue/image_name) =~ "kde" ]]; then
	flatpak override --env=XDG_CURRENT_DESKTOP=KDE
	flatpak override --user --env=XDG_CURRENT_DESKTOP=KDE
fi


# Fix printing on LibreOffice
flatpak override \
	--socket=cups \
	--socket=session-bus \
	org.libreoffice.LibreOffice

# Fix permissions for Protontricks
flatpak override \
	--filesystem="${HOME}"/.var/app/com.valvesoftware.Steam/.local/share/Steam \
	--filesystem=/var/mnt \
	--filesystem=/run/media \
	com.github.Matoking.protontricks

# Fixes too many flatpaks to list
# --env=USE_POINTER_VIEWPORT=1 fixes cursor scaling issues on GTK - revisit later
flatpak override \
	--system \
	--env=USE_POINTER_VIEWPORT=1 \
	--socket=session-bus \
	--socket=system-bus \
	--socket=wayland
flatpak override \
	--user \
	--env=USE_POINTER_VIEWPORT=1 \
	--socket=session-bus \
	--socket=system-bus \
	--socket=wayland

# Set up Zen default configuration
mkdir -p "/var/lib/flatpak/extension/io.github.zen_browser.zen.systemconfig/$(arch)/stable/defaults/pref"
rm -f "/var/lib/flatpak/extension/io.github.zen_browser.zen.systemconfig/$(arch)/stable/defaults/pref/{*sarkinite*,*arkenfox*}.js"
/usr/bin/cp -rf /usr/lib64/firefox/defaults/pref/* "/var/lib/flatpak/extension/io.github.zen_browser.zen.systemconfig/$(arch)/stable/defaults/pref/"

# Params needed for HW accelerated video on Nvidia
if [[ $(cat /etc/ublue/image_flavor) =~ "nvidia" ]] && [[ "$(grep -o "\-display" <<<"$(lshw -C display)")" -le 1 ]] && grep -q "vendor: NVIDIA Corporation" <<<"$(lshw -C display)"; then
	flatpak override \
		--system \
		--env=MOZ_ENABLE_WAYLAND=1 \
		--env=MOZ_DISABLE_RDD_SANDBOX=1 \
		io.github.zen_browser.zen
else
	flatpak override \
		--system \
		--env=MOZ_ENABLE_WAYLAND=1 \
		--unset-env=MOZ_DISABLE_RDD_SANDBOX \
		io.github.zen_browser.zen
fi

# Use until yafti rework is done
flatpak --system update -y

notify-send "Welcome to Sarkinite" "Your computer is ready!" --app-name="Flatpak Manager Service" -u NORMAL

echo "${VER}" >"${VER_FILE}"
