#!/usr/bin/bash

# Script Version
VER=1
VER_FILE="${XDG_DATA_HOME:-${HOME}/.local/share}/ublue/flatpak_manager_version"
VER_RAN=$(cat "${VER_FILE}")

mkdir -p "$(dirname "${VER_FILE}")" || exit 1

# Run script if updated
if [[ -f ${VER_FILE} && ${VER} == "${VER_RAN}" ]]; then
	echo "Flatpak manager v${VER} has already ran. Exiting..."
	exit 0
fi

# Ensure Flathub is enabled
flatpak remote-add --if-not-exists --system flathub /etc/flatpak/remotes.d/flathub.flatpakrepo
flatpak remote-modify --system --enable flathub

# Flatpak theming support
flatpak override \
	--filesystem=xdg-config/gtk-4.0:ro \
	--filesystem=xdg-config/gtk-3.0:ro \
	--filesystem=xdg-data/icons:ro

# Fix printing on LibreOffice
flatpak override \
	--system \
	--socket=cups \
	--socket=session-bus \
	org.libreoffice.LibreOffice

# Use until yafti rework is done
flatpak --system update -y

notify-send "Welcome to Sarkinite" "Your computer is ready!" --app-name="Flatpak Manager Service" -u NORMAL

echo "${VER}" >"${VER_FILE}"
