name: Sarkinite (GNOME) ISO
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '41 6 * * 2'  # 6:41 UTC every Tuesday

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-latest:
    name: Sarkinite (GNOME)
    uses: ./.github/workflows/reusable-build-iso.yml
    secrets: inherit
    with:
      brand_name: gnome
      fedora_version: stable
