name: Latest Images
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "40 4 * * 0" # 4:40 UTC Sunday
  workflow_call:
  workflow_dispatch:

jobs:
  build-image-latest:
    name: Build Latest Images
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        brand_name: ["sarkinite-kde"]
    with:
      image_flavors: '["main", "nvidia"]'
      brand_name: ${{ matrix.brand_name }}
      stream_name: latest
    # This needs splitting, right now a kernel pin will not work due to hwe kernel

  generate-release:
    name: Generate Release
    needs: [build-image-latest]
    secrets: inherit
    uses: ./.github/workflows/generate-release.yml
    with:
      stream_name: '["latest"]'
