name: GTS Images
on:
  pull_request:
    branches:
      - main
      - testing
    paths-ignore:
      - "**.md"
  workflow_dispatch:
  workflow_call:

jobs:
  build-image-gts:
    name: Build GTS Images
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        brand_name: [sarkinite-gnome]
    with:
#     kernel_pin: 6.11.3-200.fc40.x86_64     ## This is where kernels get pinned.
      brand_name: ${{ matrix.brand_name }}
      stream_name: gts

  generate_release:
    name: Generate Release
    needs: [build-image-gts]
    secrets: inherit
    uses: ./.github/workflows/generate-release.yml
    with:
      stream_name: '["gts"]'
