name: Sarkinite (Sway)
on:
  pull_request:
    branches:
      - main
      - testing
    paths-ignore:
      - "**.md"
      - "system_files/silverblue/**"
      - "system_files/kinoite/**"
  workflow_dispatch:

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      brand_name: sarkinite-sway
      fedora_version: stable
