name: Sarkinite (KDE) ISO
on:
  workflow_dispatch:
  # schedule:
  #     - cron: "41 6 1-7 * 2" # 6:41 UTC every first Tuesday of the month

jobs:
  build:
    name: Sarkinite (KDE)
    uses: ./.github/workflows/reusable-build-iso.yml
    secrets: inherit
    with:
      brand_name: sarkinite-kde
      fedora_version: stable
