name: Testing Images
on:
  merge_group:
  pull_request:
    branches:
      - main
      - testing
    paths-ignore:
      - "**.md"
  # schedule:
  #   - cron: "40 4 * * 1,2,3,4,5,6" # 4:40 UTC everyday
  #   - cron: "40 4 * * 0" # 4:40 UTC Sunday
  workflow_call:
  workflow_dispatch:

jobs:
  build-image-testing:
    name: Build Testing Images
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        brand_name: ["sarkinite"]
    with:
      brand_name: ${{ matrix.brand_name }}
      stream_name: testing

  generate-release:
    name: Generate Release
    needs: [build-image-testing]
    secrets: inherit
    uses: ./.github/workflows/generate-release.yml
    with:
      stream_name: '["testing"]'
