name: Sarkinite (KDE) ISO
on:
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    name: Sarkinite (KDE)
    uses: ./.github/workflows/reusable-build-iso.yml
    secrets: inherit
    with:
      brand_name: kde
      fedora_version: stable
