name: Build All Images
on:
  workflow_dispatch:

jobs:
  build-image-stable:
    uses: ./.github/workflows/build-image-stable.yml
    secrets: inherit
  build-image-testing:
    uses: ./.github/workflows/build-image-testing.yml
    secrets: inherit
