name: Cleanup Old Images
on:
  schedule:
    - cron: "15 0 * * 0" # 0015 UTC on Sundays
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}

jobs:
  delete-older-than-90:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete Images Older Than 90 Days
        uses: dataaxiom/ghcr-cleanup-action@792f00f0ff1466b4ee1eeb46049aeeb6ba7d1c8d # v1.0.14
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packages: sarkinite-kde,sarkinite-kde-nvidia,sarkinite-kde-dx,sarkinite-kde-dx-nvidia
          older-than: 90 days
          delete-orphaned-images: true
          keep-n-tagged: 7
          keep-n-untagged: 7
