[linux]
bootc = true

[misc]
no_self_update = true
disable = ["nix"]
ignore_failures = ["uv"]
assume_yes = true
no_retry = true
cleanup = true

[commands]
"Nix" = "command -v nix && ujust update-nix || true"
