[misc]
no_self_update = true
disable = [
  "self_update",
  "toolbx",
  "containers",
  "waydroid",
  "helm",
  "nix",
  "spicetify",
  "system",
]
ignore_failures = [
  "distrobox",
  "flatpak",
  "brew_cask",
  "brew_formula",
  "nix",
  "node",
  "pip3",
  "git_repos",
  "chezmoi",
  "helm",
  "home_manager",
  "firmware",
  "shell",
  "snap",
  "spicetify",
]
assume_yes = true
no_retry = false

[commands]
"System update" = "sudo bootc upgrade"
"Nix" = "command -v nix && ujust update-nix"
"Spicetify" = "command -v spicetify && (spicetify upgrade ; spicetify apply || spicetify restore backup apply)"
